import React from 'react';
import { Head, usePage } from '@inertiajs/react';
import { Scale, Building2, ShieldCheck, Mail } from 'lucide-react';
import ExecutiveLayout from '../../Layouts/ExecutiveLayout';

export default function Terms() {
    const { company } = usePage().props;

    return (
        <ExecutiveLayout>
            <Head title="Terms of Service — Macix AI (INCHWARD LIMITED)" />

            <div className="max-w-4xl mx-auto space-y-8 my-6">
                
                {/* Header */}
                <div className="border-b border-slate-800 pb-6">
                    <div className="inline-flex items-center gap-2 text-amber-400 text-xs font-bold uppercase tracking-wider mb-2">
                        <Scale className="w-4 h-4" />
                        <span>Corporate Legal Documentation</span>
                    </div>
                    <h1 className="text-3xl font-black text-white tracking-tight">
                        Terms of Service &amp; Business Master Agreement
                    </h1>
                    <p className="text-xs text-slate-400 mt-1">
                        Last updated: August 2026 &bull; Governing Jurisdiction: United Kingdom
                    </p>
                </div>

                {/* Operating Entity Header Box */}
                <div className="p-5 bg-[#0b101c] border border-amber-500/30 rounded-2xl flex items-start gap-4">
                    <Building2 className="w-6 h-6 text-amber-400 shrink-0 mt-1" />
                    <div className="text-xs text-slate-300 space-y-1">
                        <p className="font-bold text-white text-sm">
                            Contracting Corporate Entity: {company?.name || 'INCHWARD LIMITED'}
                        </p>
                        <p>
                            <strong>Company Number:</strong> {company?.number || '16021412'} &bull; Incorporated under the Laws of England &amp; Wales
                        </p>
                        <p>
                            <strong>Registered Office:</strong> {company?.address || 'Academy House, 11 Dunraven Place, Bridgend, Mid Glamorgan, United Kingdom, CF31 1JF'}
                        </p>
                        <p>
                            <strong>Official Desk:</strong> <a href={`mailto:${company?.email || 'info@voltoria.co.uk'}`} className="text-amber-400 hover:underline">{company?.email || 'info@voltoria.co.uk'}</a>
                        </p>
                    </div>
                </div>

                {/* Body Content */}
                <div className="space-y-6 text-xs sm:text-sm text-slate-300 leading-relaxed">
                    
                    <section className="space-y-2">
                        <h2 className="text-base font-extrabold text-white">1. Scope of Services &amp; Advisory Simulation</h2>
                        <p>
                            Macix AI ("Platform"), operated by <strong>{company?.name || 'INCHWARD LIMITED'}</strong>, provides automated, artificial intelligence-powered multi-avatar business deliberation tools for founders, executives, and enterprise decision-makers. The outputs, including but not limited to Board Meeting Minutes, Persona Opinions, and 30-Day Action Plans, are algorithmic simulations generated for strategic decision-support.
                        </p>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-base font-extrabold text-white">2. Strict Disclaimer of Fiduciary &amp; Legal Liability</h2>
                        <div className="p-4 bg-rose-500/10 border-l-2 border-rose-500 rounded-r-xl text-xs text-slate-200">
                            <strong>MANDATORY B2B DISCLAIMER:</strong> Outputs generated by the Platform do NOT constitute formal legal counsel, licensed financial advice, tax auditing, or regulated fiduciary management. All decisions, corporate reorganizations, workforce adjustments, investments, or agreements executed by the Client are undertaken at the Client's sole risk and discretion. DRAYBOND LIMITED shall not be held liable for any direct, indirect, consequential, or punitive damages resulting from business actions taken based on simulated board recommendations.
                        </div>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-base font-extrabold text-white">3. Prepaid Wallet &amp; High-Ticket Billing Terms</h2>
                        <p>
                            Platform services are rendered on a prepaid wallet model. Clients purchase internal balance credits in EUR (€) via authorized electronic payment methods. 
                        </p>
                        <ul className="list-disc pl-5 space-y-1 text-slate-400">
                            <li><strong>Starter Board (€149):</strong> Single dilemma deliberation by 4 standard personas + PDF minutes.</li>
                            <li><strong>Pro Board (€499):</strong> Customizable advisor backgrounds + prioritized 30-day action plan.</li>
                            <li><strong>Enterprise Retainer (€1,499):</strong> 10 sessions per month + financial context ingestion.</li>
                        </ul>
                        <p>
                            All transactions are recorded with strict service nomenclature, and official VAT invoices bearing 0% Reverse Charge notes are issued by DRAYBOND LIMITED.
                        </p>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-base font-extrabold text-white">4. Intellectual Property &amp; Minutes Ownership</h2>
                        <p>
                            The Client retains full, perpetual ownership and copyright over all strategic briefs submitted and all resulting Board Minutes PDFs and Resolutions generated for their account. DRAYBOND LIMITED retains all rights, title, and interest in and to the Platform architecture, proprietary prompts, design systems, and software code.
                        </p>
                    </section>

                    <section className="space-y-2">
                        <h2 className="text-base font-extrabold text-white">5. Governing Law &amp; Dispute Resolution</h2>
                        <p>
                            These Terms shall be governed by and construed in accordance with the laws of <strong>England and Wales</strong>. Any dispute, controversy, or claim arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the Courts of England and Wales.
                        </p>
                    </section>

                </div>

            </div>
        </ExecutiveLayout>
    );
}
